name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.3"

      - name: Install dependencies
        run: go mod download

      - name: Run linter
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          args: --timeout=5m

  test:
    name: Tests & Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.3"

      - name: Install dependencies
        run: go mod download

      - name: Run tests with coverage
        run: go test -v ./...

  build:
    name: Build & Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.3"

      - name: Build for multiple platforms
        run: |
          GOOS=linux GOARCH=amd64 go build -o dist/url-shortener-linux-amd64 ./cmd/server/server.go
          GOOS=darwin GOARCH=amd64 go build -o dist/url-shortener-darwin-amd64 ./cmd/server/server.go
          GOOS=windows GOARCH=amd64 go build -o dist/url-shortener-windows-amd64.exe ./cmd/server/server.go
